---
- name: Dump webhook variables
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - debug:
        msg: "{{ item }}"
      loop:
        - "{{ controller_webhook_event_type | default('Undefined') }}"
        - "{{ controller_webhook_event_guid | default('Undefined') }}"
        - "{{ controller_webhook_event_ref | default('Undefined') }}"
        - "{{ controller_webhook_status_api | default('Undefined') }}"
        - "{{ controller_webhook_payload | default('Undefined') }}"
        - "{{ tower_webhook_event_type | default('Undefined') }}"
        - "{{ tower_webhook_event_guid | default('Undefined') }}"
        - "{{ tower_webhook_event_ref | default('Undefined') }}"
        - "{{ tower_webhook_status_api | default('Undefined') }}"
        - "{{ tower_webhook_payload | default('Undefined') }}"
