---
- name: Try to find additional files
  hosts: all
  gather_facts: False
  tasks:
    - name: Cat Files
      command:
        cmd: "cat {{ item }}"
      register: cat_output
      loop: "{{ file_names }}"
      ignore_errors: True

    - debug:
        msg: "{{ cat_output }}"
