---
- name: Try to find additional files
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Cat File
      command:
        cmd: "cat {{ item }}"
      register: cat_output
      loop: "{{ file_names }}"

    - debug:
        msg: "{{ cat_output }}"
