---
- name: Run a job with a bunch of gibberish
  hosts: all
  gather_facts: False
  tasks:
    - debug:
        msg: "This is a message log"
      loop: "{{ query('sequence', 'start=1 end=128') }}"
      loop_control:
        pause: 1
